# Populate Members
CALL AddMember ('Meadow', 'Allman', 'Undeclared', 'Undeclared', 'Junior', 'mallman', 'mallman#9982', 'mallman@gmail.com', 'mallman@mail.com');
CALL AddMember ('Anayah', 'Conway', 'Software Engineering', 'Undeclared', 'Freshman', 'aconway', 'aconway#8627', 'aconway@gmail.com', '');
CALL AddMember ('Maha', 'Fitzpatrick', 'Computer Science', 'Undeclared', 'Sophomore', 'mfitzpatrick', 'mfitzpatrick#7973', 'mfitzpatrick@gmail.com', 'mfitzpatrick@unl.edu');
CALL AddMember ('Stephen', 'Mcnamara', 'Computer Science', 'Undeclared', 'Sophomore', 'smcnamara', 'smcnamara#9314', 'smcnamara@gmail.com', 'smcnamara@hotmail.com');
CALL AddMember ('Uzair', 'Nixon', 'Computer Science', 'Undeclared', 'Freshman', 'unixon', 'unixon#2619', 'unixon@gmail.com', 'unixon@unl.edu');
CALL AddMember ('Sommer', 'Fulton', 'Computer Science', 'Undeclared', 'Sophomore', 'sfulton', 'sfulton#8830', 'sfulton@gmail.com', 'sfulton@huskers.unl.edu');
CALL AddMember ('Harvey', 'Leblanc', 'Software Engineering', 'Undeclared', 'Sophomore', 'hleblanc', 'hleblanc#0079', 'hleblanc@gmail.com', 'hleblanc@gmail.com');
CALL AddMember ('JohnJames', 'Wynn', 'Computer Science', 'Undeclared', 'Sophomore', 'jwynn', 'jwynn#6719', 'jwynn@gmail.com', 'jwynn@yahoo.com');
CALL AddMember ('Eliza', 'Guest', 'Computer Engineering', 'Undeclared', 'Senior', 'eguest', 'eguest#1738', 'eguest@gmail.com', 'eguest@yandex.com');
CALL AddMember ('Efa', 'Robins', 'Computer Science', 'Undeclared', 'Sophomore', 'erobins', 'erobins#2644', 'erobins@gmail.com', 'erobins@unl.edu');
CALL AddMember ('Kelsea', 'Monaghan', 'Chemical Engineering', 'Undeclared', 'Senior', 'kmonaghan', 'kmonaghan#4522', 'kmonaghan@gmail.com', 'kmonaghan@outlook.com');
CALL AddMember ('Joe', 'Hayward', 'Computer Science', 'Undeclared', 'Freshman', 'jhayward', 'jhayward#9481', 'jhayward@gmail.com', 'jhayward@huskers.unl.edu');
CALL AddMember ('Sahar', 'Calvert', 'Computer Science', 'Undeclared', 'Sophomore', 'scalvert', 'scalvert#3309', 'scalvert@gmail.com', 'scalvert@huskers.unl.edu');
CALL AddMember ('Rudi', 'Bloom', 'Marketing', 'Undeclared', 'Sophomore', 'rbloom', 'rbloom#2029', 'rbloom@gmail.com', 'rbloom@outlook.com');
CALL AddMember ('Deen', 'Amos', 'Computer Engineering', 'Undeclared', 'Sophomore', 'damos', 'damos#1800', 'damos@gmail.com', 'damos@hotmail.com');
CALL AddMember ('Jason', 'Thompson', 'Marketing', 'Undeclared', 'Sophomore', 'jthompson', 'jthompson#1840', 'jthompson@gmail.com', 'jthompson@hotmail.com');
CALL AddMember ('Maggie', 'ODoherty', 'Computer Science', 'Undeclared', 'Junior', 'modoherty', 'modoherty#2283', 'modoherty@gmail.com', 'modoherty@gmail.com');
CALL AddMember ('Talha', 'Fowler', 'Computer Science', 'Undeclared', 'Sophomore', 'tfowler', 'tfowler#5717', 'tfowler@gmail.com', 'tfowler@huskers.unl.edu');
CALL AddMember ('Aqeel', 'Webber', 'Computer Science', 'Undeclared', 'Senior', 'awebber', 'awebber#0501', 'awebber@gmail.com', 'awebber@yandex.com');
CALL AddMember ('Mikael', 'Summers', 'Computer Science', 'Undeclared', 'Freshman', 'msummers', 'msummers#0710', 'msummers@gmail.com', 'msummers@yahoo.com');
CALL AddMember ('TylerJay', 'Rodgers', 'Computer Science', 'Undeclared', 'Sophomore', 'trodgers', 'trodgers#2336', 'trodgers@gmail.com', 'trodgers@yandex.com');
CALL AddMember ('Silas', 'Lynch', 'Computer Science', 'Undeclared', 'Freshman', 'slynch', 'slynch#0831', 'slynch@gmail.com', 'slynch@yandex.com');
CALL AddMember ('Arjan', 'Rodrigues', 'Software Engineering', 'Undeclared', 'Junior', 'arodrigues', 'arodrigues#9363', 'arodrigues@gmail.com', 'arodrigues@outlook.com');
CALL AddMember ('Tony', 'Edge', 'Software Engineering', 'Undeclared', 'Freshman', 'tedge', 'tedge#0643', 'tedge@gmail.com', 'tedge@mail.com');
CALL AddMember ('Waleed', 'Milner', 'Software Engineering', 'Undeclared', 'Sophomore', 'wmilner', 'wmilner#0349', 'wmilner@gmail.com', 'wmilner@outlook.com');
CALL AddMember ('Theia', 'Neale', 'Computer Science', 'Undeclared', 'Sophomore', 'tneale', 'tneale#2199', 'tneale@gmail.com', 'tneale@yahoo.com');
CALL AddMember ('Brittany', 'Barr', 'Computer Science', 'Undeclared', 'Junior', 'bbarr', 'bbarr#6264', 'bbarr@gmail.com', 'bbarr@unl.edu');
CALL AddMember ('Abraham', 'Davies', 'Undeclared', 'Undeclared', 'Sophomore', 'adavies', 'adavies#0606', 'adavies@gmail.com', 'adavies@hotmail.com');
CALL AddMember ('Lorenzo', 'Mccartney', 'Computer Science', 'Undeclared', 'Sophomore', 'lmccartney', 'lmccartney#3960', 'lmccartney@gmail.com', 'lmccartney@unl.edu');
CALL AddMember ('Korben', 'Tanner', 'Undeclared', 'Undeclared', 'Freshman', 'ktanner', 'ktanner#0561', 'ktanner@gmail.com', 'ktanner@unl.edu');
CALL AddMember ('Athena', 'Weber', 'Software Engineering', 'Undeclared', 'Sophomore', 'aweber', 'aweber#8609', 'aweber@gmail.com', 'aweber@mail.com');
CALL AddMember ('Osman', 'Wade', 'Software Engineering', 'Undeclared', 'Freshman', 'owade', 'owade#0269', 'owade@gmail.com', 'owade@mail.com');
CALL AddMember ('Zayyan', 'Ramsey', 'Software Engineering', 'Undeclared', 'Freshman', 'zramsey', 'zramsey#4583', 'zramsey@gmail.com', 'zramsey@huskers.unl.edu');
CALL AddMember ('Rajveer', 'Briggs', 'Software Engineering', 'Undeclared', 'Freshman', 'rbriggs', 'rbriggs#3949', 'rbriggs@gmail.com', 'rbriggs@hotmail.com');
CALL AddMember ('Mathilde', 'Nolan', 'Software Engineering', 'Undeclared', 'Freshman', 'mnolan', 'mnolan#9604', 'mnolan@gmail.com', 'mnolan@outlook.com');
CALL AddMember ('Jasmine', 'Frederick', 'Computer Science', 'Undeclared', 'Sophomore', 'jfrederick', 'jfrederick#2062', 'jfrederick@gmail.com', 'jfrederick@mail.com');
CALL AddMember ('Bhavik', 'Elliott', 'Software Engineering', 'Undeclared', 'Sophomore', 'belliott', 'belliott#0110', 'belliott@gmail.com', 'belliott@outlook.com');
CALL AddMember ('Mahi', 'Beech', 'Software Engineering', 'Undeclared', 'Sophomore', 'mbeech', 'mbeech#5380', 'mbeech@gmail.com', 'mbeech@huskers.unl.edu');
CALL AddMember ('Shirley', 'Bull', 'Computer Science', 'Undeclared', 'Sophomore', 'sbull', 'sbull#2728', 'sbull@gmail.com', 'sbull@huskers.unl.edu');
CALL AddMember ('Rayhaan', 'Ferrell', 'Undeclared', 'Undeclared', 'Freshman', 'rferrell', 'rferrell#2746', 'rferrell@gmail.com', 'rferrell@yahoo.com');
CALL AddMember ('Ellesha', 'Sosa', 'Computer Science', 'Undeclared', 'Senior', 'esosa', 'esosa#5032', 'esosa@gmail.com', 'esosa@mail.com');
CALL AddMember ('Izabel', 'Landry', 'Software Engineering', 'Undeclared', 'Freshman', 'ilandry', 'ilandry#1233', 'ilandry@gmail.com', 'ilandry@mail.com');
CALL AddMember ('Stefan', 'Mosley', 'Computer Science', 'Undeclared', 'Junior', 'smosley', 'smosley#1835', 'smosley@gmail.com', 'smosley@hotmail.com');
CALL AddMember ('Luisa', 'Ventura', 'Software Engineering', 'Undeclared', 'Junior', 'lventura', 'lventura#0079', 'lventura@gmail.com', 'lventura@unl.edu');
CALL AddMember ('LexiMai', 'Wormald', 'Computer Science', 'Undeclared', 'Sophomore', 'lwormald', 'lwormald#0089', 'lwormald@gmail.com', 'lwormald@hotmail.com');
CALL AddMember ('Rikki', 'OReilly', 'Computer Science', 'Undeclared', 'Sophomore', 'roreilly', 'roreilly#0778', 'roreilly@gmail.com', 'roreilly@unl.edu');
CALL AddMember ('Daniella', 'Hudson', 'Marketing', 'Undeclared', 'Junior', 'dhudson', 'dhudson#5971', 'dhudson@gmail.com', 'dhudson@mail.com');
CALL AddMember ('Siyana', 'Freeman', 'Undeclared', 'Undeclared', 'Sophomore', 'sfreeman', 'sfreeman#4933', 'sfreeman@gmail.com', 'sfreeman@outlook.com');
CALL AddMember ('Colleen', 'Boyce', 'Computer Science', 'Undeclared', 'Freshman', 'cboyce', 'cboyce#6542', 'cboyce@gmail.com', 'cboyce@unl.edu');
CALL AddMember ('RileyJay', 'Villa', 'Computer Science', 'Undeclared', 'Sophomore', 'rvilla', 'rvilla#4244', 'rvilla@gmail.com', 'rvilla@yahoo.com');
CALL AddMember ('Cassidy', 'Proctor', 'Computer Engineering', 'Undeclared', 'Junior', 'cproctor', 'cproctor#0641', 'cproctor@gmail.com', 'cproctor@gmail.com');
CALL AddMember ('Isla', 'Colon', 'Software Engineering', 'Undeclared', 'Freshman', 'icolon', 'icolon#4610', 'icolon@gmail.com', 'icolon@huskers.unl.edu');
CALL AddMember ('Esther', 'Lyon', 'Computer Engineering', 'Undeclared', 'Freshman', 'elyon', 'elyon#6579', 'elyon@gmail.com', 'elyon@unl.edu');
CALL AddMember ('Myla', 'Zuniga', 'Computer Engineering', 'Undeclared', 'Sophomore', 'mzuniga', 'mzuniga#4516', 'mzuniga@gmail.com', 'mzuniga@yahoo.com');
CALL AddMember ('Gordon', 'Whittle', 'Computer Science', 'Undeclared', 'Freshman', 'gwhittle', 'gwhittle#7857', 'gwhittle@gmail.com', 'gwhittle@yandex.com');
CALL AddMember ('Morris', 'Cisneros', 'Software Engineering', 'Undeclared', 'Sophomore', 'mcisneros', 'mcisneros#9541', 'mcisneros@gmail.com', 'mcisneros@unl.edu');
CALL AddMember ('Emillie', 'Dodson', 'Computer Science', 'Undeclared', 'Senior', 'edodson', 'edodson#7547', 'edodson@gmail.com', 'edodson@outlook.com');
CALL AddMember ('Albert', 'Best', 'Computer Engineering', 'Undeclared', 'Sophomore', 'abest', 'abest#5243', 'abest@gmail.com', 'abest@yahoo.com');
CALL AddMember ('Clinton', 'Roche', 'Computer Engineering', 'Undeclared', 'Freshman', 'croche', 'croche#8716', 'croche@gmail.com', 'croche@yahoo.com');
CALL AddMember ('Bjorn', 'Martin', 'Computer Science', 'Undeclared', 'Sophomore', 'bmartin', 'bmartin#7992', 'bmartin@gmail.com', 'bmartin@hotmail.com');
CALL AddMember ('Harper', 'Huff', 'Computer Science', 'Undeclared', 'Freshman', 'hhuff', 'hhuff#8178', 'hhuff@gmail.com', 'hhuff@mail.com');
CALL AddMember ('Karol', 'Stamp', 'Undeclared', 'Undeclared', 'Freshman', 'kstamp', 'kstamp#6444', 'kstamp@gmail.com', 'kstamp@unl.edu');
CALL AddMember ('Kerys', 'Wang', 'Software Engineering', 'Undeclared', 'Senior', 'kwang', 'kwang#9942', 'kwang@gmail.com', 'kwang@yandex.com');
CALL AddMember ('Lesley', 'Ridley', 'Chemical Engineering', 'Undeclared', 'Freshman', 'lridley', 'lridley#4940', 'lridley@gmail.com', 'lridley@yandex.com');
CALL AddMember ('Jax', 'Hughes', 'Undeclared', 'Undeclared', 'Senior', 'jhughes', 'jhughes#2033', 'jhughes@gmail.com', 'jhughes@outlook.com');
CALL AddMember ('Maleeha', 'Hayward', 'Computer Science', 'Undeclared', 'Sophomore', 'mhayward', 'mhayward#4375', 'mhayward@gmail.com', 'mhayward@unl.edu');
CALL AddMember ('Carlie', 'Brady', 'Software Engineering', 'Undeclared', 'Freshman', 'cbrady', 'cbrady#7089', 'cbrady@gmail.com', 'cbrady@huskers.unl.edu');
CALL AddMember ('Kendall', 'Sims', 'Undeclared', 'Undeclared', 'Junior', 'ksims', 'ksims#7069', 'ksims@gmail.com', 'ksims@yahoo.com');
CALL AddMember ('Elly', 'Pitts', 'Software Engineering', 'Undeclared', 'Junior', 'epitts', 'epitts#0322', 'epitts@gmail.com', 'epitts@huskers.unl.edu');
CALL AddMember ('Ronan', 'Webster', 'Computer Engineering', 'Undeclared', 'Junior', 'rwebster', 'rwebster#4138', 'rwebster@gmail.com', 'rwebster@mail.com');
CALL AddMember ('Carys', 'Villarreal', 'Undeclared', 'Mathematics', 'Sophomore', 'cvillarreal', 'cvillarreal#5990', 'cvillarreal@gmail.com', 'cvillarreal@yandex.com');
CALL AddMember ('Shani', 'Smart', 'Computer Engineering', 'Undeclared', 'Junior', 'ssmart', 'ssmart#3821', 'ssmart@gmail.com', '');
CALL AddMember ('Nell', 'Fuller', 'Chemical Engineering', 'Undeclared', 'Sophomore', 'nfuller', 'nfuller#4238', 'nfuller@gmail.com', 'nfuller@gmail.com');
CALL AddMember ('Meadow', 'Britt', 'Software Engineering', 'Undeclared', 'Sophomore', 'mbritt', 'mbritt#3937', 'mbritt@gmail.com', 'mbritt@yahoo.com');
CALL AddMember ('Ian', 'Summers', 'Computer Science', 'Undeclared', 'Freshman', 'isummers', 'isummers#4959', 'isummers@gmail.com', 'isummers@unl.edu');
CALL AddMember ('Vivian', 'Hagan', 'Software Engineering', 'Undeclared', 'Sophomore', 'vhagan', 'vhagan#7552', 'vhagan@gmail.com', 'vhagan@hotmail.com');
CALL AddMember ('Gracey', 'Blackburn', 'Software Engineering', 'Undeclared', 'Junior', 'gblackburn', 'gblackburn#6479', 'gblackburn@gmail.com', 'gblackburn@yandex.com');
CALL AddMember ('Beyonce', 'Cowan', 'Software Engineering', 'Undeclared', 'Freshman', 'bcowan', 'bcowan#7790', 'bcowan@gmail.com', 'bcowan@huskers.unl.edu');
CALL AddMember ('Zachariah', 'Grant', 'Undeclared', 'Undeclared', 'Sophomore', 'zgrant', 'zgrant#5378', 'zgrant@gmail.com', 'zgrant@gmail.com');
CALL AddMember ('Saad', 'Mcgee', 'Computer Science', 'Undeclared', 'Sophomore', 'smcgee', 'smcgee#8880', 'smcgee@gmail.com', 'smcgee@yahoo.com');
CALL AddMember ('Clarissa', 'Nicholson', 'Computer Science', 'Undeclared', 'Sophomore', 'cnicholson', 'cnicholson#9163', 'cnicholson@gmail.com', 'cnicholson@yandex.com');
CALL AddMember ('Lamar', 'Boyce', 'Software Engineering', 'Undeclared', 'Sophomore', 'lboyce', 'lboyce#5240', 'lboyce@gmail.com', '');
CALL AddMember ('Grady', 'Rankin', 'Computer Science', 'Mathematics', 'Sophomore', 'grankin', 'grankin#1078', 'grankin@gmail.com', 'grankin@yahoo.com');
CALL AddMember ('Nadia', 'Ibarra', 'Computer Engineering', 'Undeclared', 'Sophomore', 'nibarra', 'nibarra#4578', 'nibarra@gmail.com', 'nibarra@yahoo.com');
CALL AddMember ('Emir', 'Vasquez', 'Computer Engineering', 'Undeclared', 'Junior', 'evasquez', 'evasquez#5202', 'evasquez@gmail.com', 'evasquez@huskers.unl.edu');
CALL AddMember ('Keeley', 'Dixon', 'Computer Science', 'Undeclared', 'Freshman', 'kdixon', 'kdixon#2886', 'kdixon@gmail.com', 'kdixon@hotmail.com');
CALL AddMember ('Bronwen', 'Winters', 'Software Engineering', 'Undeclared', 'Junior', 'bwinters', 'bwinters#8351', 'bwinters@gmail.com', 'bwinters@mail.com');
CALL AddMember ('Macauly', 'Burks', 'Undeclared', 'Undeclared', 'Freshman', 'mburks', 'mburks#0280', 'mburks@gmail.com', 'mburks@outlook.com');
CALL AddMember ('Grace', 'Galvan', 'Computer Science', 'Undeclared', 'Sophomore', 'ggalvan', 'ggalvan#3889', 'ggalvan@gmail.com', 'ggalvan@yandex.com');
CALL AddMember ('Lewis', 'Callahan', 'Computer Science', 'Undeclared', 'Sophomore', 'lcallahan', 'lcallahan#7103', 'lcallahan@gmail.com', 'lcallahan@unl.edu');
CALL AddMember ('Jorja', 'Coles', 'Software Engineering', 'Undeclared', 'Freshman', 'jcoles', 'jcoles#8671', 'jcoles@gmail.com', 'jcoles@yandex.com');
CALL AddMember ('Zephaniah', 'Mays', 'Computer Engineering', 'Undeclared', 'Sophomore', 'zmays', 'zmays#2059', 'zmays@gmail.com', 'zmays@hotmail.com');
CALL AddMember ('Caroline', 'Santana', 'Computer Science', 'Undeclared', 'Junior', 'csantana', 'csantana#5148', 'csantana@gmail.com', 'csantana@mail.com');
CALL AddMember ('Harvie', 'Holcomb', 'Computer Science', 'Undeclared', 'Senior', 'hholcomb', 'hholcomb#7851', 'hholcomb@gmail.com', 'hholcomb@yandex.com');
CALL AddMember ('Ivie', 'Dunkley', 'Undeclared', 'Undeclared', 'Senior', 'idunkley', 'idunkley#8432', 'idunkley@gmail.com', 'idunkley@huskers.unl.edu');
CALL AddMember ('Alvin', 'Arias', 'Computer Science', 'Undeclared', 'Sophomore', 'aarias', 'aarias#2355', 'aarias@gmail.com', 'aarias@yandex.com');
CALL AddMember ('Saskia', 'Fenton', 'Computer Science', 'Undeclared', 'Freshman', 'sfenton', 'sfenton#7497', 'sfenton@gmail.com', 'sfenton@mail.com');
CALL AddMember ('Findlay', 'Koch', 'Software Engineering', 'Undeclared', 'Sophomore', 'fkoch', 'fkoch#7184', 'fkoch@gmail.com', 'fkoch@mail.com');
CALL AddMember ('Borys', 'Gentry', 'Undeclared', 'Undeclared', 'Sophomore', 'bgentry', 'bgentry#4375', 'bgentry@gmail.com', 'bgentry@hotmail.com');
CALL AddMember ('Karis', 'Howells', 'Undeclared', 'Undeclared', 'Sophomore', 'khowells', 'khowells#0329', 'khowells@gmail.com', 'khowells@outlook.com');
