# Populate Members
CALL AddMember ('Meadow', 'Allman', 'Software Engineering', 'Undeclared', 'Freshman', 'mallman', 'mallman#3218', 'mallman@gmail.com', 'mallman@gmail.com');
CALL AddMember ('Anayah', 'Conway', 'Computer Science', 'Undeclared', 'Sophomore', 'aconway', 'aconway#0394', 'aconway@gmail.com', 'aconway@hotmail.com');
CALL AddMember ('Maha', 'Fitzpatrick', 'Undeclared', 'Undeclared', 'Freshman', 'mfitzpatrick', 'mfitzpatrick#9840', 'mfitzpatrick@gmail.com', 'mfitzpatrick@yandex.com');
CALL AddMember ('Stephen', 'Mcnamara', 'Computer Engineering', 'Undeclared', 'Sophomore', 'smcnamara', 'smcnamara#4500', 'smcnamara@gmail.com', 'smcnamara@hotmail.com');
CALL AddMember ('Uzair', 'Nixon', 'Software Engineering', 'Undeclared', 'Junior', 'unixon', 'unixon#1496', 'unixon@gmail.com', 'unixon@gmail.com');
CALL AddMember ('Sommer', 'Fulton', 'Computer Science', 'Mathematics', 'Sophomore', 'sfulton', 'sfulton#2360', 'sfulton@gmail.com', 'sfulton@unl.edu');
CALL AddMember ('Harvey', 'Leblanc', 'Computer Science', 'Undeclared', 'Sophomore', 'hleblanc', 'hleblanc#5861', 'hleblanc@gmail.com', 'hleblanc@unl.edu');
CALL AddMember ('JohnJames', 'Wynn', 'Undeclared', 'Undeclared', 'Sophomore', 'jwynn', 'jwynn#0995', 'jwynn@gmail.com', 'jwynn@huskers.unl.edu');
CALL AddMember ('Eliza', 'Guest', 'Marketing', 'Undeclared', 'Masters', 'eguest', 'eguest#4791', 'eguest@gmail.com', 'eguest@outlook.com');
CALL AddMember ('Efa', 'Robins', 'Computer Science', 'Undeclared', 'Junior', 'erobins', 'erobins#1329', 'erobins@gmail.com', 'erobins@yandex.com');
CALL AddMember ('Kelsea', 'Monaghan', 'Computer Science', 'Undeclared', 'Junior', 'kmonaghan', 'kmonaghan#4886', 'kmonaghan@gmail.com', 'kmonaghan@outlook.com');
CALL AddMember ('Joe', 'Hayward', 'Computer Science', 'Undeclared', 'Sophomore', 'jhayward', 'jhayward#8302', 'jhayward@gmail.com', 'jhayward@huskers.unl.edu');
CALL AddMember ('Sahar', 'Calvert', 'Computer Science', 'Undeclared', 'Senior', 'scalvert', 'scalvert#5866', 'scalvert@gmail.com', 'scalvert@huskers.unl.edu');
CALL AddMember ('Rudi', 'Bloom', 'Software Engineering', 'Undeclared', 'Sophomore', 'rbloom', 'rbloom#4380', 'rbloom@gmail.com', 'rbloom@gmail.com');
CALL AddMember ('Deen', 'Amos', 'Computer Science', 'Undeclared', 'Sophomore', 'damos', 'damos#1054', 'damos@gmail.com', 'damos@huskers.unl.edu');
CALL AddMember ('Jason', 'Thompson', 'Computer Science', 'Undeclared', 'Sophomore', 'jthompson', 'jthompson#2985', 'jthompson@gmail.com', 'jthompson@unl.edu');
CALL AddMember ('Maggie', 'ODoherty', 'Computer Science', 'Undeclared', 'Masters', 'modoherty', 'modoherty#2261', 'modoherty@gmail.com', 'modoherty@gmail.com');
CALL AddMember ('Talha', 'Fowler', 'Computer Science', 'Undeclared', 'Sophomore', 'tfowler', 'tfowler#7723', 'tfowler@gmail.com', 'tfowler@outlook.com');
CALL AddMember ('Aqeel', 'Webber', 'Computer Science', 'Undeclared', 'Freshman', 'awebber', 'awebber#3371', 'awebber@gmail.com', 'awebber@gmail.com');
CALL AddMember ('Mikael', 'Summers', 'Software Engineering', 'Undeclared', 'Junior', 'msummers', 'msummers#1093', 'msummers@gmail.com', 'msummers@yandex.com');
CALL AddMember ('TylerJay', 'Rodgers', 'Computer Science', 'Undeclared', 'Senior', 'trodgers', 'trodgers#8308', 'trodgers@gmail.com', 'trodgers@yandex.com');
CALL AddMember ('Silas', 'Lynch', 'Undeclared', 'Undeclared', 'Junior', 'slynch', 'slynch#7061', 'slynch@gmail.com', 'slynch@mail.com');
CALL AddMember ('Arjan', 'Rodrigues', 'Software Engineering', 'Undeclared', 'Freshman', 'arodrigues', 'arodrigues#2811', 'arodrigues@gmail.com', 'arodrigues@gmail.com');
CALL AddMember ('Tony', 'Edge', 'Computer Science', 'Undeclared', 'Junior', 'tedge', 'tedge#5566', 'tedge@gmail.com', 'tedge@yahoo.com');
CALL AddMember ('Waleed', 'Milner', 'Computer Science', 'Undeclared', 'Junior', 'wmilner', 'wmilner#5157', 'wmilner@gmail.com', 'wmilner@huskers.unl.edu');
CALL AddMember ('Theia', 'Neale', 'Undeclared', 'Undeclared', 'Sophomore', 'tneale', 'tneale#8998', 'tneale@gmail.com', 'tneale@outlook.com');
CALL AddMember ('Brittany', 'Barr', 'Software Engineering', 'Undeclared', 'Freshman', 'bbarr', 'bbarr#8868', 'bbarr@gmail.com', 'bbarr@hotmail.com');
CALL AddMember ('Abraham', 'Davies', 'Computer Engineering', 'Undeclared', 'Freshman', 'adavies', 'adavies#2302', 'adavies@gmail.com', 'adavies@gmail.com');
CALL AddMember ('Lorenzo', 'Mccartney', 'Computer Engineering', 'Undeclared', 'Sophomore', 'lmccartney', 'lmccartney#6218', 'lmccartney@gmail.com', 'lmccartney@outlook.com');
CALL AddMember ('Korben', 'Tanner', 'Computer Science', 'Undeclared', 'Junior', 'ktanner', 'ktanner#1717', 'ktanner@gmail.com', 'ktanner@yandex.com');
CALL AddMember ('Athena', 'Weber', 'Computer Science', 'Undeclared', 'Freshman', 'aweber', 'aweber#6733', 'aweber@gmail.com', 'aweber@gmail.com');
CALL AddMember ('Osman', 'Wade', 'Chemical Engineering', 'Undeclared', 'Freshman', 'owade', 'owade#2713', 'owade@gmail.com', 'owade@huskers.unl.edu');
CALL AddMember ('Zayyan', 'Ramsey', 'Computer Science', 'Undeclared', 'Sophomore', 'zramsey', 'zramsey#9934', 'zramsey@gmail.com', '');
CALL AddMember ('Rajveer', 'Briggs', 'English', 'Undeclared', 'Sophomore', 'rbriggs', 'rbriggs#7891', 'rbriggs@gmail.com', 'rbriggs@gmail.com');
CALL AddMember ('Mathilde', 'Nolan', 'Computer Engineering', 'Undeclared', 'Junior', 'mnolan', 'mnolan#0054', 'mnolan@gmail.com', 'mnolan@gmail.com');
CALL AddMember ('Jasmine', 'Frederick', 'Chemical Engineering', 'Undeclared', 'Senior', 'jfrederick', 'jfrederick#0740', 'jfrederick@gmail.com', 'jfrederick@yandex.com');
CALL AddMember ('Bhavik', 'Elliott', 'Computer Engineering', 'Undeclared', 'Sophomore', 'belliott', 'belliott#4062', 'belliott@gmail.com', 'belliott@hotmail.com');
CALL AddMember ('Mahi', 'Beech', 'Computer Science', 'Undeclared', 'Junior', 'mbeech', 'mbeech#7022', 'mbeech@gmail.com', 'mbeech@huskers.unl.edu');
CALL AddMember ('Shirley', 'Bull', 'Computer Science', 'Undeclared', 'Freshman', 'sbull', 'sbull#8165', 'sbull@gmail.com', 'sbull@gmail.com');
CALL AddMember ('Rayhaan', 'Ferrell', 'Undeclared', 'Undeclared', 'Sophomore', 'rferrell', 'rferrell#5497', 'rferrell@gmail.com', 'rferrell@yahoo.com');
CALL AddMember ('Ellesha', 'Sosa', 'Software Engineering', 'Undeclared', 'Sophomore', 'esosa', 'esosa#7681', 'esosa@gmail.com', 'esosa@yandex.com');
CALL AddMember ('Izabel', 'Landry', 'Undeclared', 'Undeclared', 'Junior', 'ilandry', 'ilandry#2087', 'ilandry@gmail.com', 'ilandry@huskers.unl.edu');
CALL AddMember ('Stefan', 'Mosley', 'Computer Science', 'Undeclared', 'Junior', 'smosley', 'smosley#7881', 'smosley@gmail.com', 'smosley@gmail.com');
CALL AddMember ('Luisa', 'Ventura', 'Software Engineering', 'Undeclared', 'Sophomore', 'lventura', 'lventura#8540', 'lventura@gmail.com', 'lventura@yahoo.com');
CALL AddMember ('LexiMai', 'Wormald', 'Software Engineering', 'Undeclared', 'Junior', 'lwormald', 'lwormald#8320', 'lwormald@gmail.com', 'lwormald@huskers.unl.edu');
CALL AddMember ('Rikki', 'OReilly', 'Software Engineering', 'Undeclared', 'Sophomore', 'roreilly', 'roreilly#1529', 'roreilly@gmail.com', 'roreilly@unl.edu');
CALL AddMember ('Daniella', 'Hudson', 'Undeclared', 'Undeclared', 'Sophomore', 'dhudson', 'dhudson#6096', 'dhudson@gmail.com', 'dhudson@mail.com');
CALL AddMember ('Siyana', 'Freeman', 'Software Engineering', 'Undeclared', 'Senior', 'sfreeman', 'sfreeman#1184', 'sfreeman@gmail.com', 'sfreeman@yandex.com');
CALL AddMember ('Colleen', 'Boyce', 'Computer Engineering', 'Undeclared', 'Freshman', 'cboyce', 'cboyce#7880', 'cboyce@gmail.com', 'cboyce@yahoo.com');
CALL AddMember ('RileyJay', 'Villa', 'Undeclared', 'Undeclared', 'Junior', 'rvilla', 'rvilla#0089', 'rvilla@gmail.com', '');
CALL AddMember ('Cassidy', 'Proctor', 'Computer Engineering', 'Undeclared', 'Junior', 'cproctor', 'cproctor#1056', 'cproctor@gmail.com', 'cproctor@unl.edu');
CALL AddMember ('Isla', 'Colon', 'Marketing', 'Undeclared', 'Junior', 'icolon', 'icolon#2148', 'icolon@gmail.com', 'icolon@outlook.com');
CALL AddMember ('Esther', 'Lyon', 'Undeclared', 'Undeclared', 'Sophomore', 'elyon', 'elyon#9783', 'elyon@gmail.com', 'elyon@yahoo.com');
CALL AddMember ('Myla', 'Zuniga', 'Computer Science', 'Undeclared', 'Sophomore', 'mzuniga', 'mzuniga#0935', 'mzuniga@gmail.com', 'mzuniga@hotmail.com');
CALL AddMember ('Gordon', 'Whittle', 'Computer Science', 'Mathematics', 'Sophomore', 'gwhittle', 'gwhittle#3544', 'gwhittle@gmail.com', 'gwhittle@huskers.unl.edu');
CALL AddMember ('Morris', 'Cisneros', 'Undeclared', 'Undeclared', 'Sophomore', 'mcisneros', 'mcisneros#1049', 'mcisneros@gmail.com', 'mcisneros@yahoo.com');
CALL AddMember ('Emillie', 'Dodson', 'Computer Science', 'Undeclared', 'Sophomore', 'edodson', 'edodson#0180', 'edodson@gmail.com', 'edodson@huskers.unl.edu');
CALL AddMember ('Albert', 'Best', 'Computer Science', 'Undeclared', 'Sophomore', 'abest', 'abest#9883', 'abest@gmail.com', 'abest@outlook.com');
CALL AddMember ('Clinton', 'Roche', 'Software Engineering', 'Undeclared', 'Sophomore', 'croche', 'croche#0053', 'croche@gmail.com', 'croche@unl.edu');
CALL AddMember ('Bjorn', 'Martin', 'Computer Science', 'Undeclared', 'Freshman', 'bmartin', 'bmartin#6561', 'bmartin@gmail.com', 'bmartin@huskers.unl.edu');
CALL AddMember ('Harper', 'Huff', 'Software Engineering', 'Undeclared', 'Sophomore', 'hhuff', 'hhuff#4293', 'hhuff@gmail.com', 'hhuff@yandex.com');
CALL AddMember ('Karol', 'Stamp', 'Software Engineering', 'Undeclared', 'Freshman', 'kstamp', 'kstamp#8489', 'kstamp@gmail.com', 'kstamp@unl.edu');
CALL AddMember ('Kerys', 'Wang', 'Software Engineering', 'Undeclared', 'Sophomore', 'kwang', 'kwang#4200', 'kwang@gmail.com', 'kwang@gmail.com');
CALL AddMember ('Lesley', 'Ridley', 'Computer Science', 'Undeclared', 'Freshman', 'lridley', 'lridley#4528', 'lridley@gmail.com', 'lridley@gmail.com');
CALL AddMember ('Jax', 'Hughes', 'Software Engineering', 'Undeclared', 'Junior', 'jhughes', 'jhughes#8359', 'jhughes@gmail.com', 'jhughes@outlook.com');
CALL AddMember ('Maleeha', 'Hayward', 'Computer Science', 'Undeclared', 'Sophomore', 'mhayward', 'mhayward#8929', 'mhayward@gmail.com', 'mhayward@outlook.com');
CALL AddMember ('Carlie', 'Brady', 'Computer Science', 'Undeclared', 'Junior', 'cbrady', 'cbrady#3616', 'cbrady@gmail.com', 'cbrady@hotmail.com');
CALL AddMember ('Kendall', 'Sims', 'Computer Science', 'Undeclared', 'Sophomore', 'ksims', 'ksims#5566', 'ksims@gmail.com', 'ksims@yahoo.com');
CALL AddMember ('Elly', 'Pitts', 'Undeclared', 'Undeclared', 'Freshman', 'epitts', 'epitts#0861', 'epitts@gmail.com', 'epitts@yahoo.com');
CALL AddMember ('Ronan', 'Webster', 'Undeclared', 'Undeclared', 'Sophomore', 'rwebster', 'rwebster#1573', 'rwebster@gmail.com', 'rwebster@outlook.com');
CALL AddMember ('Carys', 'Villarreal', 'Undeclared', 'Undeclared', 'Sophomore', 'cvillarreal', 'cvillarreal#1051', 'cvillarreal@gmail.com', 'cvillarreal@yahoo.com');
CALL AddMember ('Shani', 'Smart', 'Computer Science', 'Undeclared', 'Junior', 'ssmart', 'ssmart#2387', 'ssmart@gmail.com', 'ssmart@yahoo.com');
CALL AddMember ('Nell', 'Fuller', 'Undeclared', 'Undeclared', 'Freshman', 'nfuller', 'nfuller#4584', 'nfuller@gmail.com', 'nfuller@huskers.unl.edu');
CALL AddMember ('Meadow', 'Britt', 'Computer Science', 'Mathematics', 'Junior', 'mbritt', 'mbritt#3001', 'mbritt@gmail.com', 'mbritt@yahoo.com');
CALL AddMember ('Ian', 'Summers', 'Undeclared', 'Undeclared', 'Sophomore', 'isummers', 'isummers#1052', 'isummers@gmail.com', '');
CALL AddMember ('Vivian', 'Hagan', 'Software Engineering', 'Mathematics', 'Sophomore', 'vhagan', 'vhagan#3399', 'vhagan@gmail.com', 'vhagan@mail.com');
CALL AddMember ('Gracey', 'Blackburn', 'Computer Science', 'Undeclared', 'Sophomore', 'gblackburn', 'gblackburn#2130', 'gblackburn@gmail.com', 'gblackburn@unl.edu');
CALL AddMember ('Beyonce', 'Cowan', 'Computer Science', 'Undeclared', 'Sophomore', 'bcowan', 'bcowan#9897', 'bcowan@gmail.com', 'bcowan@outlook.com');
CALL AddMember ('Zachariah', 'Grant', 'Software Engineering', 'Undeclared', 'Sophomore', 'zgrant', 'zgrant#6790', 'zgrant@gmail.com', 'zgrant@yandex.com');
CALL AddMember ('Saad', 'Mcgee', 'Computer Science', 'Undeclared', 'Junior', 'smcgee', 'smcgee#3793', 'smcgee@gmail.com', 'smcgee@hotmail.com');
CALL AddMember ('Clarissa', 'Nicholson', 'Software Engineering', 'Undeclared', 'Sophomore', 'cnicholson', 'cnicholson#7912', 'cnicholson@gmail.com', 'cnicholson@huskers.unl.edu');
CALL AddMember ('Lamar', 'Boyce', 'Computer Engineering', 'Undeclared', 'Senior', 'lboyce', 'lboyce#0520', 'lboyce@gmail.com', 'lboyce@hotmail.com');
CALL AddMember ('Grady', 'Rankin', 'Computer Engineering', 'Undeclared', 'Sophomore', 'grankin', 'grankin#9390', 'grankin@gmail.com', 'grankin@gmail.com');
CALL AddMember ('Nadia', 'Ibarra', 'Computer Science', 'Undeclared', 'Sophomore', 'nibarra', 'nibarra#7305', 'nibarra@gmail.com', 'nibarra@huskers.unl.edu');
CALL AddMember ('Emir', 'Vasquez', 'Computer Science', 'Undeclared', 'Senior', 'evasquez', 'evasquez#3619', 'evasquez@gmail.com', 'evasquez@unl.edu');
CALL AddMember ('Keeley', 'Dixon', 'Marketing', 'Undeclared', 'Sophomore', 'kdixon', 'kdixon#5965', 'kdixon@gmail.com', 'kdixon@hotmail.com');
CALL AddMember ('Bronwen', 'Winters', 'Computer Science', 'Undeclared', 'Senior', 'bwinters', 'bwinters#0618', 'bwinters@gmail.com', 'bwinters@yahoo.com');
CALL AddMember ('Macauly', 'Burks', 'Computer Engineering', 'Undeclared', 'Freshman', 'mburks', 'mburks#5178', 'mburks@gmail.com', 'mburks@mail.com');
CALL AddMember ('Grace', 'Galvan', 'Software Engineering', 'Undeclared', 'Sophomore', 'ggalvan', 'ggalvan#1545', 'ggalvan@gmail.com', 'ggalvan@yahoo.com');
CALL AddMember ('Lewis', 'Callahan', 'Software Engineering', 'Undeclared', 'Junior', 'lcallahan', 'lcallahan#1611', 'lcallahan@gmail.com', 'lcallahan@yandex.com');
CALL AddMember ('Jorja', 'Coles', 'Computer Science', 'Undeclared', 'Junior', 'jcoles', 'jcoles#8070', 'jcoles@gmail.com', 'jcoles@yahoo.com');
CALL AddMember ('Zephaniah', 'Mays', 'Computer Science', 'Mathematics', 'Freshman', 'zmays', 'zmays#3997', 'zmays@gmail.com', 'zmays@hotmail.com');
CALL AddMember ('Caroline', 'Santana', 'Software Engineering', 'Undeclared', 'Senior', 'csantana', 'csantana#0135', 'csantana@gmail.com', 'csantana@huskers.unl.edu');
CALL AddMember ('Harvie', 'Holcomb', 'Computer Science', 'Undeclared', 'Sophomore', 'hholcomb', 'hholcomb#8552', 'hholcomb@gmail.com', 'hholcomb@yahoo.com');
CALL AddMember ('Ivie', 'Dunkley', 'Undeclared', 'Undeclared', 'Freshman', 'idunkley', 'idunkley#6360', 'idunkley@gmail.com', 'idunkley@yahoo.com');
CALL AddMember ('Alvin', 'Arias', 'Computer Science', 'Undeclared', 'Junior', 'aarias', 'aarias#3355', 'aarias@gmail.com', 'aarias@gmail.com');
CALL AddMember ('Saskia', 'Fenton', 'Computer Science', 'Undeclared', 'Freshman', 'sfenton', 'sfenton#2906', 'sfenton@gmail.com', 'sfenton@hotmail.com');
CALL AddMember ('Findlay', 'Koch', 'Undeclared', 'Undeclared', 'Sophomore', 'fkoch', 'fkoch#7446', 'fkoch@gmail.com', 'fkoch@hotmail.com');
CALL AddMember ('Borys', 'Gentry', 'Marketing', 'Undeclared', 'Junior', 'bgentry', 'bgentry#9088', 'bgentry@gmail.com', 'bgentry@outlook.com');
CALL AddMember ('Karis', 'Howells', 'Computer Science', 'Undeclared', 'Sophomore', 'khowells', 'khowells#8148', 'khowells@gmail.com', 'khowells@unl.edu');
