# Populate MembersCALL AddMember ('Meadow', 'Allman', 'Computer Science', 'Undeclared', 'Sophomore', 'mallman', 'mallman#9429', 'mallman@gmail.com', 'mallman@unl.edu');
CALL AddMember ('Anayah', 'Conway', 'Computer Engineering', 'Undeclared', 'Senior', 'aconway', 'aconway#3178', 'aconway@gmail.com', 'aconway@yahoo.com');
CALL AddMember ('Maha', 'Fitzpatrick', 'Computer Science', 'Undeclared', 'Junior', 'mfitzpatrick', 'mfitzpatrick#2436', 'mfitzpatrick@gmail.com', 'mfitzpatrick@yandex.com');
CALL AddMember ('Stephen', 'Mcnamara', 'Undeclared', 'Undeclared', 'Senior', 'smcnamara', 'smcnamara#9853', 'smcnamara@gmail.com', 'smcnamara@outlook.com');
CALL AddMember ('Uzair', 'Nixon', 'Computer Science', 'Undeclared', 'Freshman', 'unixon', 'unixon#4551', 'unixon@gmail.com', 'unixon@mail.com');
CALL AddMember ('Sommer', 'Fulton', 'Computer Engineering', 'Undeclared', 'Sophomore', 'sfulton', 'sfulton#9131', 'sfulton@gmail.com', 'sfulton@yandex.com');
CALL AddMember ('Harvey', 'Leblanc', 'Computer Science', 'Undeclared', 'Senior', 'hleblanc', 'hleblanc#3598', 'hleblanc@gmail.com', 'hleblanc@yandex.com');
CALL AddMember ('JohnJames', 'Wynn', 'Computer Science', 'Undeclared', 'Freshman', 'jwynn', 'jwynn#1665', 'jwynn@gmail.com', 'jwynn@yahoo.com');
CALL AddMember ('Eliza', 'Guest', 'Computer Science', 'Undeclared', 'Freshman', 'eguest', 'eguest#8767', 'eguest@gmail.com', 'eguest@yahoo.com');
CALL AddMember ('Efa', 'Robins', 'Computer Science', 'Undeclared', 'Junior', 'erobins', 'erobins#1216', 'erobins@gmail.com', 'erobins@yandex.com');
CALL AddMember ('Kelsea', 'Monaghan', 'Undeclared', 'Undeclared', 'Senior', 'kmonaghan', 'kmonaghan#3462', 'kmonaghan@gmail.com', 'kmonaghan@yandex.com');
CALL AddMember ('Joe', 'Hayward', 'Software Engineering', 'Undeclared', 'Senior', 'jhayward', 'jhayward#5803', 'jhayward@gmail.com', 'jhayward@yahoo.com');
CALL AddMember ('Sahar', 'Calvert', 'Software Engineering', 'Undeclared', 'Freshman', 'scalvert', 'scalvert#1293', 'scalvert@gmail.com', '');
CALL AddMember ('Rudi', 'Bloom', 'Software Engineering', 'Mathematics', 'Senior', 'rbloom', 'rbloom#0611', 'rbloom@gmail.com', 'rbloom@yandex.com');
CALL AddMember ('Deen', 'Amos', 'Software Engineering', 'Undeclared', 'Sophomore', 'damos', 'damos#0237', 'damos@gmail.com', 'damos@huskers.unl.edu');
CALL AddMember ('Jason', 'Thompson', 'Computer Science', 'Mathematics', 'Sophomore', 'jthompson', 'jthompson#7040', 'jthompson@gmail.com', '');
CALL AddMember ('Maggie', 'ODoherty', 'Undeclared', 'Undeclared', 'Junior', 'modoherty', 'modoherty#6578', 'modoherty@gmail.com', 'modoherty@mail.com');
CALL AddMember ('Talha', 'Fowler', 'Software Engineering', 'Undeclared', 'Sophomore', 'tfowler', 'tfowler#6206', 'tfowler@gmail.com', 'tfowler@unl.edu');
CALL AddMember ('Aqeel', 'Webber', 'Computer Science', 'Undeclared', 'Junior', 'awebber', 'awebber#4745', 'awebber@gmail.com', '');
CALL AddMember ('Mikael', 'Summers', 'Computer Science', 'Undeclared', 'Sophomore', 'msummers', 'msummers#8783', 'msummers@gmail.com', 'msummers@mail.com');
CALL AddMember ('TylerJay', 'Rodgers', 'Software Engineering', 'Undeclared', 'Freshman', 'trodgers', 'trodgers#0349', 'trodgers@gmail.com', 'trodgers@gmail.com');
CALL AddMember ('Silas', 'Lynch', 'Undeclared', 'Undeclared', 'Freshman', 'slynch', 'slynch#7155', 'slynch@gmail.com', 'slynch@gmail.com');
CALL AddMember ('Arjan', 'Rodrigues', 'Computer Engineering', 'Undeclared', 'Sophomore', 'arodrigues', 'arodrigues#8878', 'arodrigues@gmail.com', 'arodrigues@gmail.com');
CALL AddMember ('Tony', 'Edge', 'Software Engineering', 'Undeclared', 'Freshman', 'tedge', 'tedge#6830', 'tedge@gmail.com', 'tedge@yahoo.com');
CALL AddMember ('Waleed', 'Milner', 'Software Engineering', 'Mathematics', 'Masters', 'wmilner', 'wmilner#1975', 'wmilner@gmail.com', 'wmilner@mail.com');
CALL AddMember ('Theia', 'Neale', 'Computer Science', 'Undeclared', 'Freshman', 'tneale', 'tneale#4991', 'tneale@gmail.com', '');
CALL AddMember ('Brittany', 'Barr', 'English', 'Undeclared', 'Junior', 'bbarr', 'bbarr#8079', 'bbarr@gmail.com', '');
CALL AddMember ('Abraham', 'Davies', 'Computer Engineering', 'Undeclared', 'Freshman', 'adavies', 'adavies#5152', 'adavies@gmail.com', 'adavies@yandex.com');
CALL AddMember ('Lorenzo', 'Mccartney', 'Undeclared', 'Undeclared', 'Junior', 'lmccartney', 'lmccartney#8957', 'lmccartney@gmail.com', 'lmccartney@yahoo.com');
CALL AddMember ('Korben', 'Tanner', 'Software Engineering', 'Undeclared', 'Sophomore', 'ktanner', 'ktanner#0842', 'ktanner@gmail.com', 'ktanner@yandex.com');
CALL AddMember ('Athena', 'Weber', 'Computer Science', 'Undeclared', 'Sophomore', 'aweber', 'aweber#2991', 'aweber@gmail.com', '');
CALL AddMember ('Osman', 'Wade', 'Software Engineering', 'Undeclared', 'Sophomore', 'owade', 'owade#0475', 'owade@gmail.com', 'owade@yandex.com');
CALL AddMember ('Zayyan', 'Ramsey', 'Software Engineering', 'Undeclared', 'Sophomore', 'zramsey', 'zramsey#3033', 'zramsey@gmail.com', 'zramsey@huskers.unl.edu');
CALL AddMember ('Rajveer', 'Briggs', 'Undeclared', 'Undeclared', 'Sophomore', 'rbriggs', 'rbriggs#6935', 'rbriggs@gmail.com', 'rbriggs@mail.com');
CALL AddMember ('Mathilde', 'Nolan', 'Computer Science', 'Undeclared', 'Sophomore', 'mnolan', 'mnolan#6658', 'mnolan@gmail.com', 'mnolan@huskers.unl.edu');
CALL AddMember ('Jasmine', 'Frederick', 'Computer Science', 'Undeclared', 'Sophomore', 'jfrederick', 'jfrederick#3454', 'jfrederick@gmail.com', 'jfrederick@mail.com');
CALL AddMember ('Bhavik', 'Elliott', 'Computer Engineering', 'Mathematics', 'Junior', 'belliott', 'belliott#8732', 'belliott@gmail.com', 'belliott@unl.edu');
CALL AddMember ('Mahi', 'Beech', 'Software Engineering', 'Undeclared', 'Sophomore', 'mbeech', 'mbeech#5366', 'mbeech@gmail.com', 'mbeech@gmail.com');
CALL AddMember ('Shirley', 'Bull', 'Computer Science', 'Undeclared', 'Freshman', 'sbull', 'sbull#2885', 'sbull@gmail.com', 'sbull@yandex.com');
CALL AddMember ('Rayhaan', 'Ferrell', 'Undeclared', 'Undeclared', 'Sophomore', 'rferrell', 'rferrell#1831', 'rferrell@gmail.com', 'rferrell@outlook.com');
CALL AddMember ('Ellesha', 'Sosa', 'Computer Engineering', 'Undeclared', 'Junior', 'esosa', 'esosa#3929', 'esosa@gmail.com', 'esosa@unl.edu');
CALL AddMember ('Izabel', 'Landry', 'Computer Science', 'Undeclared', 'Freshman', 'ilandry', 'ilandry#4321', 'ilandry@gmail.com', 'ilandry@yahoo.com');
CALL AddMember ('Stefan', 'Mosley', 'Undeclared', 'Undeclared', 'Junior', 'smosley', 'smosley#2303', 'smosley@gmail.com', 'smosley@yandex.com');
CALL AddMember ('Luisa', 'Ventura', 'Computer Engineering', 'Undeclared', 'Junior', 'lventura', 'lventura#6312', 'lventura@gmail.com', 'lventura@mail.com');
CALL AddMember ('LexiMai', 'Wormald', 'Computer Engineering', 'Mathematics', 'Senior', 'lwormald', 'lwormald#4692', 'lwormald@gmail.com', '');
CALL AddMember ('Rikki', 'OReilly', 'Computer Science', 'Mathematics', 'Freshman', 'roreilly', 'roreilly#9084', 'roreilly@gmail.com', 'roreilly@yandex.com');
CALL AddMember ('Daniella', 'Hudson', 'Software Engineering', 'Undeclared', 'Sophomore', 'dhudson', 'dhudson#6528', 'dhudson@gmail.com', 'dhudson@hotmail.com');
CALL AddMember ('Siyana', 'Freeman', 'Software Engineering', 'Undeclared', 'Freshman', 'sfreeman', 'sfreeman#9317', 'sfreeman@gmail.com', 'sfreeman@hotmail.com');
CALL AddMember ('Colleen', 'Boyce', 'Undeclared', 'Undeclared', 'Sophomore', 'cboyce', 'cboyce#4219', 'cboyce@gmail.com', 'cboyce@yahoo.com');
CALL AddMember ('RileyJay', 'Villa', 'Software Engineering', 'Undeclared', 'Sophomore', 'rvilla', 'rvilla#0454', 'rvilla@gmail.com', 'rvilla@gmail.com');
CALL AddMember ('Cassidy', 'Proctor', 'Computer Science', 'Undeclared', 'Sophomore', 'cproctor', 'cproctor#0802', 'cproctor@gmail.com', 'cproctor@huskers.unl.edu');
CALL AddMember ('Isla', 'Colon', 'Undeclared', 'Undeclared', 'Sophomore', 'icolon', 'icolon#3220', 'icolon@gmail.com', 'icolon@gmail.com');
CALL AddMember ('Esther', 'Lyon', 'Computer Science', 'Undeclared', 'Freshman', 'elyon', 'elyon#1789', 'elyon@gmail.com', 'elyon@hotmail.com');
CALL AddMember ('Myla', 'Zuniga', 'Computer Engineering', 'Undeclared', 'Sophomore', 'mzuniga', 'mzuniga#8547', 'mzuniga@gmail.com', 'mzuniga@outlook.com');
CALL AddMember ('Gordon', 'Whittle', 'Software Engineering', 'Undeclared', 'Junior', 'gwhittle', 'gwhittle#2785', 'gwhittle@gmail.com', 'gwhittle@gmail.com');
CALL AddMember ('Morris', 'Cisneros', 'Computer Engineering', 'Undeclared', 'Sophomore', 'mcisneros', 'mcisneros#7033', 'mcisneros@gmail.com', 'mcisneros@mail.com');
CALL AddMember ('Emillie', 'Dodson', 'Computer Science', 'Undeclared', 'Junior', 'edodson', 'edodson#4039', 'edodson@gmail.com', 'edodson@huskers.unl.edu');
CALL AddMember ('Albert', 'Best', 'Computer Engineering', 'Undeclared', 'Junior', 'abest', 'abest#9102', 'abest@gmail.com', 'abest@huskers.unl.edu');
CALL AddMember ('Clinton', 'Roche', 'Marketing', 'Mathematics', 'Senior', 'croche', 'croche#6312', 'croche@gmail.com', 'croche@mail.com');
CALL AddMember ('Bjorn', 'Martin', 'Computer Science', 'Undeclared', 'Freshman', 'bmartin', 'bmartin#7901', 'bmartin@gmail.com', '');
CALL AddMember ('Harper', 'Huff', 'Computer Engineering', 'Undeclared', 'Freshman', 'hhuff', 'hhuff#7698', 'hhuff@gmail.com', 'hhuff@yandex.com');
CALL AddMember ('Karol', 'Stamp', 'Software Engineering', 'Undeclared', 'Sophomore', 'kstamp', 'kstamp#5181', 'kstamp@gmail.com', 'kstamp@hotmail.com');
CALL AddMember ('Kerys', 'Wang', 'Computer Science', 'Undeclared', 'Masters', 'kwang', 'kwang#6010', 'kwang@gmail.com', 'kwang@yahoo.com');
CALL AddMember ('Lesley', 'Ridley', 'Computer Engineering', 'Undeclared', 'Freshman', 'lridley', 'lridley#2774', 'lridley@gmail.com', 'lridley@mail.com');
CALL AddMember ('Jax', 'Hughes', 'Undeclared', 'Undeclared', 'Junior', 'jhughes', 'jhughes#4796', 'jhughes@gmail.com', 'jhughes@yandex.com');
CALL AddMember ('Maleeha', 'Hayward', 'Computer Science', 'Undeclared', 'Junior', 'mhayward', 'mhayward#6235', 'mhayward@gmail.com', 'mhayward@hotmail.com');
CALL AddMember ('Carlie', 'Brady', 'Software Engineering', 'Undeclared', 'Sophomore', 'cbrady', 'cbrady#7624', 'cbrady@gmail.com', 'cbrady@huskers.unl.edu');
CALL AddMember ('Kendall', 'Sims', 'Software Engineering', 'Undeclared', 'Freshman', 'ksims', 'ksims#4372', 'ksims@gmail.com', 'ksims@mail.com');
CALL AddMember ('Elly', 'Pitts', 'Software Engineering', 'Undeclared', 'Sophomore', 'epitts', 'epitts#5969', 'epitts@gmail.com', 'epitts@mail.com');
CALL AddMember ('Ronan', 'Webster', 'Software Engineering', 'Undeclared', 'Sophomore', 'rwebster', 'rwebster#1198', 'rwebster@gmail.com', 'rwebster@hotmail.com');
CALL AddMember ('Carys', 'Villarreal', 'Computer Science', 'Undeclared', 'Sophomore', 'cvillarreal', 'cvillarreal#1983', 'cvillarreal@gmail.com', 'cvillarreal@gmail.com');
CALL AddMember ('Shani', 'Smart', 'Computer Science', 'Undeclared', 'Sophomore', 'ssmart', 'ssmart#7417', 'ssmart@gmail.com', 'ssmart@unl.edu');
CALL AddMember ('Nell', 'Fuller', 'Computer Science', 'Undeclared', 'Sophomore', 'nfuller', 'nfuller#0988', 'nfuller@gmail.com', 'nfuller@unl.edu');
CALL AddMember ('Meadow', 'Britt', 'Undeclared', 'Undeclared', 'Junior', 'mbritt', 'mbritt#7011', 'mbritt@gmail.com', 'mbritt@unl.edu');
CALL AddMember ('Ian', 'Summers', 'Computer Science', 'Undeclared', 'Freshman', 'isummers', 'isummers#2603', 'isummers@gmail.com', 'isummers@outlook.com');
CALL AddMember ('Vivian', 'Hagan', 'Computer Engineering', 'Mathematics', 'Sophomore', 'vhagan', 'vhagan#1154', 'vhagan@gmail.com', '');
CALL AddMember ('Gracey', 'Blackburn', 'Computer Science', 'Mathematics', 'Junior', 'gblackburn', 'gblackburn#5851', 'gblackburn@gmail.com', 'gblackburn@huskers.unl.edu');
CALL AddMember ('Beyonce', 'Cowan', 'Software Engineering', 'Undeclared', 'Freshman', 'bcowan', 'bcowan#8447', 'bcowan@gmail.com', 'bcowan@hotmail.com');
CALL AddMember ('Zachariah', 'Grant', 'Software Engineering', 'Undeclared', 'Sophomore', 'zgrant', 'zgrant#8223', 'zgrant@gmail.com', 'zgrant@outlook.com');
CALL AddMember ('Saad', 'Mcgee', 'Software Engineering', 'Undeclared', 'Freshman', 'smcgee', 'smcgee#7311', 'smcgee@gmail.com', 'smcgee@hotmail.com');
CALL AddMember ('Clarissa', 'Nicholson', 'Software Engineering', 'Undeclared', 'Sophomore', 'cnicholson', 'cnicholson#9373', 'cnicholson@gmail.com', 'cnicholson@mail.com');
CALL AddMember ('Lamar', 'Boyce', 'Software Engineering', 'Undeclared', 'Senior', 'lboyce', 'lboyce#8958', 'lboyce@gmail.com', 'lboyce@gmail.com');
CALL AddMember ('Grady', 'Rankin', 'Computer Engineering', 'Undeclared', 'Sophomore', 'grankin', 'grankin#5523', 'grankin@gmail.com', 'grankin@yahoo.com');
CALL AddMember ('Nadia', 'Ibarra', 'Software Engineering', 'Undeclared', 'Sophomore', 'nibarra', 'nibarra#0632', 'nibarra@gmail.com', 'nibarra@hotmail.com');
CALL AddMember ('Emir', 'Vasquez', 'Computer Science', 'Undeclared', 'Sophomore', 'evasquez', 'evasquez#4241', 'evasquez@gmail.com', 'evasquez@gmail.com');
CALL AddMember ('Keeley', 'Dixon', 'Computer Science', 'Undeclared', 'Freshman', 'kdixon', 'kdixon#9572', 'kdixon@gmail.com', 'kdixon@yandex.com');
CALL AddMember ('Bronwen', 'Winters', 'Computer Science', 'Undeclared', 'Freshman', 'bwinters', 'bwinters#5403', 'bwinters@gmail.com', 'bwinters@yahoo.com');
CALL AddMember ('Macauly', 'Burks', 'Computer Science', 'Undeclared', 'Sophomore', 'mburks', 'mburks#9736', 'mburks@gmail.com', 'mburks@yahoo.com');
CALL AddMember ('Grace', 'Galvan', 'Software Engineering', 'Undeclared', 'Senior', 'ggalvan', 'ggalvan#4742', 'ggalvan@gmail.com', 'ggalvan@huskers.unl.edu');
CALL AddMember ('Lewis', 'Callahan', 'Computer Science', 'Undeclared', 'Junior', 'lcallahan', 'lcallahan#6057', 'lcallahan@gmail.com', 'lcallahan@gmail.com');
CALL AddMember ('Jorja', 'Coles', 'Computer Science', 'Undeclared', 'Freshman', 'jcoles', 'jcoles#7044', 'jcoles@gmail.com', 'jcoles@outlook.com');
CALL AddMember ('Zephaniah', 'Mays', 'Computer Science', 'Undeclared', 'Junior', 'zmays', 'zmays#1678', 'zmays@gmail.com', 'zmays@yahoo.com');
CALL AddMember ('Caroline', 'Santana', 'Computer Science', 'Undeclared', 'Freshman', 'csantana', 'csantana#7800', 'csantana@gmail.com', 'csantana@huskers.unl.edu');
CALL AddMember ('Harvie', 'Holcomb', 'Computer Science', 'Undeclared', 'Freshman', 'hholcomb', 'hholcomb#6023', 'hholcomb@gmail.com', 'hholcomb@unl.edu');
CALL AddMember ('Ivie', 'Dunkley', 'Software Engineering', 'Undeclared', 'Sophomore', 'idunkley', 'idunkley#8144', 'idunkley@gmail.com', 'idunkley@yandex.com');
CALL AddMember ('Alvin', 'Arias', 'Undeclared', 'Undeclared', 'Freshman', 'aarias', 'aarias#3673', 'aarias@gmail.com', 'aarias@huskers.unl.edu');
CALL AddMember ('Saskia', 'Fenton', 'Computer Science', 'Undeclared', 'Sophomore', 'sfenton', 'sfenton#5073', 'sfenton@gmail.com', 'sfenton@huskers.unl.edu');
CALL AddMember ('Findlay', 'Koch', 'Undeclared', 'Undeclared', 'Sophomore', 'fkoch', 'fkoch#0240', 'fkoch@gmail.com', '');
CALL AddMember ('Borys', 'Gentry', 'Computer Science', 'Undeclared', 'Junior', 'bgentry', 'bgentry#5846', 'bgentry@gmail.com', '');
CALL AddMember ('Karis', 'Howells', 'Computer Engineering', 'Undeclared', 'Freshman', 'khowells', 'khowells#1783', 'khowells@gmail.com', 'khowells@outlook.com');
